# Generated by Django 4.2.2 on 2023-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='game_name',
            field=models.CharField(default='GTA', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='slug-one', max_length=70),
        ),
    ]
