# Generated by Django 4.2.2 on 2023-06-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Article',
        ),
    ]
