# Generated by Django 4.2.2 on 2023-06-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_blog_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('R', 'Review'), ('N', 'News'), ('O', 'Opinion'), ('H', 'Hardware')], default='R', max_length=10),
        ),
    ]
