# Generated by Django 4.2.2 on 2023-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('REVIEW', 'Review'), ('NEWS', 'News'), ('OPINION', 'Opinion'), ('HARDWARE', 'Hardware')], default='Review', max_length=10),
        ),
    ]
