# Generated by Django 4.2.2 on 2023-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Review', 'Review'), ('News', 'News'), ('Opinion', 'Opinion'), ('Hardware', 'Hardware')], default='Review', max_length=10),
        ),
    ]
